FROM jenkins/jenkins:lts

USER root

# Install tools
RUN apt update && apt install -y \
    maven \
    docker.io \
    curl

# Install kubectl
RUN curl -LO "https://dl.k8s.io/release/v1.29.0/bin/linux/amd64/kubectl" \
    && install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

USER jenkins